### ISSUE TITLE
Not building

### ISSUE THREAD

**Issue by AverTry** [jessety/pm2-installer#15]
**Description**

Copied folder from zip : "pm2-installer-main"
Ran : npm run bundle & npm run setup. Also ran : npm i to see if that was needed same result!
**script-for-os is intended for use from an npm script only**

**Environment**
[Execute `npm run info` and paste the result here]
Running on: 03/02/2021, pm2-installer 3.1.2 with node v15.5.0 and npm 7.3.0 on win32-10.0.19042.
![image](https://user-images.githubusercontent.com/72357571/106771909-65145d80-6637-11eb-92db-809fd4beedcb.png)

**Comment by jessety** [comment]
I'm about 90% sure this is an npm 7 issue. Thanks for reporting!
