### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by pkandra** [jessety/pm2-installer#38]
**Description**
Last step:  npm run setup fails on a new windows machine

**Steps to Reproduce**
1.  npm run configure
2.  npm run configure-policy
3.  npm run setup

**Environment**
[Execute `npm run info` and paste the result here]
C:\pm2-installer-main>npm run info

> pm2-installer@3.2.3 info C:\pm2-installer-main
> node ./src/bundle-info/current.js

Running on: 8/23/2021, pm2-installer 3.2.3 with node v14.17.5 and npm 6.14.14 on win32-10.0.14393.
[2021-08-23T20_49_20_619Z-debug.log](https://github.com/jessety/pm2-installer/files/7034815/2021-08-23T20_49_20_619Z-debug.log)

**Comment by pkandra** [comment]
Just to post a follow up, I ran:
npm install -g node-windows

and then npm run setup ran fine and created the service.
The service appears to run and then stop though.  It's set to automatic, but I'm not sure if it should be running all the time or just on a reboot.

**Comment by jessety** [comment]
Hi @pkandra! Version `v3.2.4` should fix the 1st problem in this issue. I suspect the intermittent service issue you reported is an unrelated issue
