### ISSUE TITLE
Could not find "pm2.exe"

### ISSUE THREAD

**Issue by hosvfx** [jessety/pm2-installer#48]
@jessety  I follow all the instructions to install this package and every time it give me this error below is there way to resolve this issue?

""Could not find "pm2.exe" service after 10 attempts.
At C:\pm2-installer-main\src\windows\setup-service.ps1:124 char:5
+     throw "Could not find `"$name`" service after $maxAttempts attemp ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...er 10 attempts.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find "pm2.exe" service after 10 attempts.

**Comment by xinthose** [comment]
What is your operating system?

**Comment by hosvfx** [comment]
> What is your operating system?

@xinthose operating system Windows Server 2019.

**Comment by xinthose** [comment]
OK.  I have successfully installed this on Windows Server 2019.  Some other servers of the same version I have trouble with.  I am not sure of the exact cause.  I do not know if it is related to security / organization settings.  Are you using the Node.js command prompt as administrator?

**Comment by hosvfx** [comment]
Hi @xinthose, yes I use Node.js command prompt as administrator. Is this maybe because security issue or organization sitting as you mention above if so is there way to check this before send to IT about this issue.
Thank you and appreciate your help.

**Comment by jessety** [comment]
Hi @hosvfx, was this an online or offline installation?

**Comment by SarasArya** [comment]
Hey @jessety mine was an online installation and I am still facing this issue? Any resolutions?
