### ISSUE TITLE
Could not start service: Service Dependency Failure

### ISSUE THREAD

**Issue by danilodecanini** [jessety/pm2-installer#5]
When I execute  `npm run setup` the script install everything with success but when its time to start the service, I got a message like:

**Could not start service: Service Dependency Failure
No C:\pm2-installer\src\windows\setup-service.ps1:182 caractere:5
    throw could not start service: $message
    CategoryInfo          : OperationStopped: (Could not start...endency Failure:String) [], RuntimeException
FullyQualifiedErrorId : Could not start service: Service Dependency Failure**

I tried to install with the rewrite service branch, but I got the same error message.

If I go to services.msc there is a service called PM2 but I got almost the same error that is in script.

My Local Service User is on the local administrators group I don't think that is something related to permission.

**Comment by danilodecanini** [comment]
**Update:**
Workaround: I change manually the user that runs PM2 service, instead of NT AUTORITHY\LOCAL SERVICE I used the Local service user, Idk what is the difference between them but now the service is running

**Comment by jessety** [comment]
Thank you! This is great. I'd heard of this issue before, but was never able to replicate it.

What version of Node do you have installed? What version of Windows are you running, and what is your system's base language?

**Comment by danilodecanini** [comment]
Hi, @jessety 

Node version: v12.17.0
SO version: Windows Server 2016 Standard x64
Base language: Português Brasil

Output from PS:
Confirm-Service -name "pm2.exe"
Found "pm2.exe" service:
  State: Running
  Status: OK
  Started: True
  Start Mode: Auto
  Service Type: Own Process
  Start Name: NT AUTHORITY\LocalService

**Comment by jessety** [comment]
It seems like this is an issue for all Windows installations where the base language isn't English. Yikes. A fix is now live in the [service-dependency-fix](https://github.com/jessety/pm2-installer/tree/service-dependency-fix) branch.

@danilodecanini Try it out! If it works for you I'll merge #6.

Thanks again!

**Comment by danilodecanini** [comment]
With this fix it works with success! 

Thank you so much for this quick fix!

**Comment by jessety** [comment]
Thanks for reporting it! 🎉👍
