### ISSUE TITLE
Failed to set permissions on "C:\ProgramData\pm2\home"

### ISSUE THREAD

**Issue by dev-syn** [jessety/pm2-installer#85]
## Description

When trying to run the setup I get this output

```
Attempting to grant "NT AUTHORITY\LOCAL SERVICE" full permissions to "C:\ProgramData\pm2\home".
Failed to set permissions on "C:\ProgramData\pm2\home". Details: The 'Get-Acl' command was found in the module
'Microsoft.PowerShell.Security', but the module could not be loaded. For more information, run 'Import-Module
Microsoft.PowerShell.Security'.
At C:\Tools\pm2-installer-main\src\windows\setup-service.ps1:52 char:5
+     throw "Failed to set permissions on `"$Directory`". Details: $_"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to set p...hell.Security'.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to set permissions on "C:\ProgramData\pm2\home". Details: The 'Get-Acl' command w
   as found in the module 'Microsoft.PowerShell.Security', but the module could not be loaded. For more information,
  run 'Import-Module Microsoft.PowerShell.Security'.
```

I'm running PowerShell 7.3.4

## Steps to Reproduce

1. Admin: Terminal
2. After running configure
3. npm run setup

## Environment

6/9/2023, pm2-installer 3.4.3 with node v18.14.2 and npm 9.6.4 on win32-10.0.22621.

**Comment by dev-syn** [comment]
I think it was a user permissions problem within ProgramData

**Comment by ghost** [comment]
@dev-syn How did you solve this ? Nothing seems to work.

**Comment by ghost** [comment]
"npm run setup" works on the old powershell started as a terminal but not on the new one.

**Comment by dev-syn** [comment]
> "npm run setup" works on the old powershell started as a terminal but not on the new one.

Good to know to be honest I gave up because I thought it was a problem within my own computer with permissions. I did a reset recently and haven't touched permissions nor tried setting this up again but when I do I will try that

**Comment by ghost** [comment]
> > "npm run setup" works on the old powershell started as a terminal but not on the new one.
> 
> Good to know to be honest I gave up because I thought it was a problem within my own computer with permissions. I did a reset recently and haven't touched permissions nor tried setting this up again but when I do I will try that

I'm lucky enough to have to have full access to my work machine but I'm restricted to a windows environment due to certain factors so I ended up practically trying everything in a weekend. 
I still encounter this https://github.com/jessety/pm2-installer/issues/86 but once I change to "Local System Account" I didn't encounter any other problems except the one where pm2 doesn't care about 'npm' on Windows and you have to pass on the full npm-cli.js path as 'script' in the ecosystem file.

**Comment by Aki-Siponen** [comment]
> I'm running PowerShell 7.3.4

The cause of this error is incompatibility of PowerShell Core (pwsh, version 7.x) and PowerShell (version 5.x) core modules, specifically Microsoft.PowerShell.Security.
npm runs the setup in PowerShell, not in PowerShell Core.
When you try to run setup from pwsh, what setup is doing is starting Command Prompt to start node to start Command Prompt to ... start PowerShell.
PowerShell is effectively running on top of pwsh. I guess that PowerShell does not support loading core modules in this situation. At least document [here](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility?view=powershell-7.4#managing-cmdlet-clobbering) explains that (starting from PowerShell 7.1) core PowerShell modules cannot be loaded in compatibility mode.

You could get rid of the error by adding these lines to start of src/windows/setup.ps1:

```
# Write-Host "Checking how this all started."
# Get-Process -Id $PID
$wmi = Get-WmiObject Win32_Process -Filter "ProcessId=$($pid)"
do {
  $process = Get-Process -Id $wmi.ParentProcessId -ErrorAction SilentlyContinue
  # $process # for debugging
  if ($process.Name -eq 'pwsh') {
    Write-Host "The  setup cannot be started from PowerShell Core (pwsh, PowerShell version 7.x).`nPlease run the setup from Powershell (version 5.x)."
    exit(1)
  }
  $wmi = Get-WmiObject Win32_Process -Filter "ProcessId=$($wmi.ParentProcessId)" -ErrorAction SilentlyContinue
} until ($wmi.ParentProcessId -eq $null)
```
That would prevent setup running in PowerShell Core.

If you would want to run setup in PowerShell Core, you'd need to change "PowerShell" to "pwsh" in all package.json scripts.

**Comment by dev-syn** [comment]
> > I'm running PowerShell 7.3.4
> 
> The cause of this error is incompatibility of PowerShell Core (pwsh, version 7.x) and PowerShell (version 5.x) core modules, specifically Microsoft.PowerShell.Security. npm runs the setup in PowerShell, not in PowerShell Core. When you try to run setup from pwsh, what setup is doing is starting Command Prompt to start node to start Command Prompt to ... start PowerShell. PowerShell is effectively running on top of pwsh. I guess that PowerShell does not support loading core modules in this situation. At least document [here](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility?view=powershell-7.4#managing-cmdlet-clobbering) explains that (starting from PowerShell 7.1) core PowerShell modules cannot be loaded in compatibility mode.
> 
> You could get rid of the error by adding these lines to start of src/windows/setup.ps1:
> 
> ```
> # Write-Host "Checking how this all started."
> # Get-Process -Id $PID
> $wmi = Get-WmiObject Win32_Process -Filter "ProcessId=$($pid)"
> do {
>   $process = Get-Process -Id $wmi.ParentProcessId -ErrorAction SilentlyContinue
>   # $process # for debugging
>   if ($process.Name -eq 'pwsh') {
>     Write-Host "The  setup cannot be started from PowerShell Core (pwsh, PowerShell version 7.x).`nPlease run the setup from Powershell (version 5.x)."
>     exit(1)
>   }
>   $wmi = Get-WmiObject Win32_Process -Filter "ProcessId=$($wmi.ParentProcessId)" -ErrorAction SilentlyContinue
> } until ($wmi.ParentProcessId -eq $null)
> ```
> 
> That would prevent setup running in PowerShell Core.
> 
> If you would want to run setup in PowerShell Core, you'd need to change "PowerShell" to "pwsh" in all package.json scripts.

Thanks for pointing this out if I return to pm2 I will definitely remember this.
